# Generated by Django 5.0.4 on 2024-05-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PR_Sub_category_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Category_PD', models.CharField(blank=True, max_length=100, null=True)),
                ('Sub_Description_PD', models.CharField(blank=True, max_length=200, null=True)),
                ('Sub_Image_PD', models.ImageField(blank=True, null=True, upload_to='PedalRushers_Images')),
            ],
        ),
    ]
