# Generated by Django 5.0.4 on 2024-05-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_pr_sub_category_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pr_sub_category_db',
            old_name='Sub_Category_PD',
            new_name='Sub_Category',
        ),
    ]
