# Generated by Django 5.0.4 on 2024-05-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_rename_sub_category_pd_pr_sub_category_db_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr_sub_category_db',
            name='Sub_Image_PD',
            field=models.ImageField(blank=True, null=True, upload_to='Sub_category_images'),
        ),
    ]
