# Generated by Django 5.0.4 on 2024-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_alter_pr_sub_category_db_sub_image_pd'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr_sub_category_db',
            name='Sub_Models',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pr_sub_category_db',
            name='Sub_Description_PD',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
