# Generated by Django 5.0.4 on 2024-05-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_pr_sub_category_db_sub_models_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PR_Product_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('Pro_Model', models.CharField(blank=True, max_length=200, null=True)),
                ('Pro_Price', models.IntegerField(blank=True, null=True)),
                ('Pro_Brand', models.CharField(blank=True, max_length=200, null=True)),
                ('Pro_Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Pro_Img', models.ImageField(blank=True, null=True, upload_to='Product_images')),
            ],
        ),
    ]
