# Generated by Django 5.0.4 on 2024-05-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_pr_product_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='PR_Technical_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tec_Product', models.CharField(blank=True, max_length=200, null=True)),
                ('Tec_Description', models.CharField(blank=True, max_length=600, null=True)),
                ('Tec_Age', models.CharField(blank=True, max_length=50, null=True)),
                ('Tec_Color', models.CharField(blank=True, max_length=50, null=True)),
                ('Tec_Material', models.CharField(blank=True, max_length=100, null=True)),
                ('Tec_Size', models.CharField(blank=True, max_length=50, null=True)),
                ('Tec_Features', models.CharField(blank=True, max_length=200, null=True)),
                ('Tec_Style', models.CharField(blank=True, max_length=100, null=True)),
                ('Tec_Components', models.CharField(blank=True, max_length=200, null=True)),
                ('Tec_Weight', models.CharField(blank=True, max_length=100, null=True)),
                ('Tec_ModelNo', models.CharField(blank=True, max_length=100, null=True)),
                ('Tec_Manufacture', models.CharField(blank=True, max_length=100, null=True)),
                ('Tec_Orgin', models.CharField(blank=True, max_length=100, null=True)),
                ('Tec_Prsin', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
