# Generated by Django 5.0.4 on 2024-05-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_pr_technical_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr_technical_db',
            name='Tec_Features',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
