# Generated by Django 5.0.4 on 2024-06-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBillingDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Postalcode', models.IntegerField(blank=True, null=True)),
                ('Messages', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
